[package]
name = "chunk"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
actix-files = "0.6.8"
actix-multipart = "0.7.2"
tokio = { version = "1", features = ["fs"] }  
sanitize-filename = "0.6.0"
serde = "1.0.228"
